version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Containerfile
    container_name: transaction-server
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    networks:
      - transaction-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Containerfile
    container_name: transaction-client
    ports:
      - "4173:4173"
    depends_on:
      - server
    networks:
      - transaction-network
    restart: unless-stopped

networks:
  transaction-network:
    driver: bridge